### PR TITLE
Standardise file naming, header guards

### PR DESCRIPTION
**Pull request by willgittoes-dd**
Standardises source file naming on TitleCase.ext, which is more windowsy than the alternative snake_case.ext. 

Same deal with header guards. There was a mix of #defines and #pragma onces, and I settled on the latter as being more common in windows code.

### CODE REVIEW

**Comment by lucaspimentel** [comment]
@willgittoes-dd: You and @dd-caleb should agree on one style for filenames and `#pragma once`. Looks like you both are moving things in different directions. Caleb has been renaming file from CamelCase to snake_case, recently, and changing `#pragma once` to `#ifdef`. Let's just pick one style guide (Google C++ Style Guide?) and stick to it.

And don't worry about the C++ code being more "Windows-y." It will need to compile on Linux at some point, too.

**Comment by dd-caleb** [comment]
Yeah I had been removing the pragmas and renaming the files to match the google style guide. Don't have a strong opinion one way or the other, but if we use `pragma once` we should make sure it works in non-windows.

**Comment by willgittoes-dd** [comment]
eyyyy, try this one instead: https://github.com/DataDog/dd-trace-csharp/pull/103

**Comment by lucaspimentel** [comment]
We're going with #103 instead. Thanks!

**Pull request closed without merging**
